language: node_js
before_script:
- sudo curl -LO http://xrl.us/cpanm
- sudo chmod +x cpanm
- sudo ./cpanm Net::OAuth
- cd test/clients/ruby
- bundle install
- cd ../../../
- sudo pip install requests-oauth
- npm install -g bunyan
deploy:
  provider: npm
  email: ryan@ryanbreen.com
  api_key:
    secure: bwhZIXKniloMQz6+dJUMECUTLbG7j24wPwuG9G/H/YiMd6I7Z9P2roeeIC7TKu/NzXGLjySzqPYDxIZm9VGonx2lY4rOVC0vDkju2iEY3PIzAU8aO2FP9mFdaE03PN5bFwoB1BheHYypyOalPFZ6Zugq+RmM8SftyscdjhhFuRc=
after_success:
- node_modules/coveralls/bin/coveralls.js < reports/lcov.info