language: node_js
node_js:
  - 0.12.7
sudo: false
install:
  - npm cache clean
  - npm install -g bunyan grunt grunt-cli
  - npm update
  - npm install
before_script:
  # Install Ruby depenencies (used by Ruby client in unit tests)
  - bundle install --gemfile=test/clients/ruby/Gemfile
  # Install Perl dependencies (used by Perl client in unit tests)
  - export PERL_MM_USE_DEFAULT=1 PERL_LOCAL_LIB_ROOT=$HOME/perl5 PERL5LIB=$HOME/perl5/lib/perl5
  - curl -L https://cpanmin.us/ -o ~/perl5/bin/cpanm && chmod +x ~/perl5/bin/cpanm
  - ~/perl5/bin/cpanm --installdeps --notest Net::OAuth LWP::UserAgent HTTP::Request::Common
  # Install Python dependencies (used by Python client in unit tests)
  # fix via https://github.com/rande/travis-kitchensink/blob/48e5915be37a4141dc59a8fd5c06b807c4abbab8/.travis.yml
  - export PATH=$HOME/.local/bin:$PATH
  - pip install requests-oauth  --user `whoami`
script:
  - npm test
after_success:
  - npm run coveralls
deploy:
  provider: npm
  email: ryan@ryanbreen.com
  on:
    tags: true
    all_branches: true
  api_key:
    secure: HhcCSWt/gIavho8apRa3+8UWgAesoJ1o2dvbhROviIZ+XNYBm5qCo1dfTH9d5hhaOVVVXe7rKLcqwru57fahXefU7gzPu78FuBQA5ipQnwQCZg8tLPVrq9FRGYUXOd/e/Al7NB9yVLaP6ji4KHC0lNUsEGMeo9mrH0hpKy9mc+k=
