language: node_js
node_js:
- 0.12.7
sudo: false
install:
- npm cache clean
- npm install -g npm@latest
- npm install -g bunyan grunt grunt-cli
- npm update
- npm install
before_script:
- bundle install --gemfile=test/clients/ruby/Gemfile
- export PATH=$HOME/.local/bin:$PATH
- pip install requests-oauth --user `whoami`
script:
- npm test
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: mail@theopak.com
  on:
    tags: true
    all_branches: true
  api_key:
    secure: VeEgOEeiHBROgfHFmHjK6sJJ0yqydM5EIXNq4gpuhWS6xrPOnR0iD3g4aejNCnlre7F5ld7FetnBAvvPs03lm+oR5Sl2YIRYIGAXPnBEl8zNSWK/uborf/JZ2Vrhn3Er8Evsq6+goZ9U3D8LmrjrjznAS1uY+/KXs9DBL6+064w=
