language: node_js
node_js:
  - 0.12.7
sudo: false
install:
  - npm cache clean
  - npm install -g bunyan grunt grunt-cli
  - npm update
  - npm install
before_script:
  # Install Ruby depenencies (used by Ruby client in unit tests)
  - bundle install --gemfile=test/clients/ruby/Gemfile
  # Install Perl dependencies (used by Perl client in unit tests)
  # - export PERL_MM_USE_DEFAULT=1 PERL_LOCAL_LIB_ROOT=$HOME/perl5 PERL5LIB=$HOME/perl5/lib/perl5 PERL_MB_OPT='--install_base "'$HOME'/perl5"' && env | grep PERL && which perl cpan cpanm || true
  # - mkdir -p $HOME/perl5/bin/ && curl -L https://cpanmin.us/ -o $HOME/perl5/bin/cpanm && chmod +x $HOME/perl5/bin/cpanm
  # - $HOME/perl5/bin/cpanm --installdeps --notest Net::OAuth LWP::UserAgent HTTP::Request::Common
  # Install Python dependencies (used by Python client in unit tests)
  # fix via https://github.com/rande/travis-kitchensink/blob/48e5915be37a4141dc59a8fd5c06b807c4abbab8/.travis.yml
  - export PATH=$HOME/.local/bin:$PATH
  - pip install requests-oauth --user `whoami`
script:
  - npm test
after_success:
  - npm run coveralls
deploy:
  provider: npm
  email: mail@theopak.com
  on:
    tags: true
    all_branches: true
  api_key:
    secure: FiUaN8GCOnUTBAQPi8uW2bs8xV254zmLMpgWrDllePHJJH911ADHMdfrTYqXJiailVDoedXZJnWNAJsf17cDpJn5W+SN+LklDVMTUJ36P+UiZjVgTVxrxGrNxbkbI8rBrzMudzpE4gYn1hIMYB0fAPGpgZ+W4rT31B+LKvVQq9vgcPvbMwvEITWJelVDgIBEf4IybT7GHRaP32MRuvOZUhX5Z2uCqVte0qma5iOOTPnSOTbmgXzfDclf+3wHHQ6UFhgCEbrPM6UdbsfgOP1WfDVxVk0b0i34anRwURHdst/U/ecKhmBR0r2hMtyfuBUJwpgW+fTjbXK358J6/IcLTsOV3yJhvBzT+Io2yZPm86izEQsVblRbPIMNX/af0Fld/AVFlw4flrJ9eMCZkgFZR78PIe4hvu0li79siFrJDbm9ISWjUhTfkYbpkvRz1UVyDaWYBskkUd686jXVCtil4htfZ/CuuowG4yxD31RLGvPfKVsjpHz843HfxFnsp732dDEyix9LV2BDuVf6R/ZBHLPUVFGEKPEwf1YTN6OffaKgpoVUQkUvhb8+OQG8BoxoYdf0UOok06igNfvckufUxolY7TLFg2cTsfDooG7L18125EPDq5WuuEFh3dP/yn6YIg19NqI7BH/sjDt7fQ/hp+L05qzgnKnD6LWLAa/Gvi4=
