language: node_js
node_js:
  - 0.12.7
sudo: false
install:
  - npm cache clean
  - npm install -g bunyan grunt grunt-cli
  - npm install
  - npm update
  - npm install
  - npm install
before_script:
  - cd test/clients/ruby
  - bundle install
  - cd ../../../
  # via https://github.com/rande/travis-kitchensink/blob/48e5915be37a4141dc59a8fd5c06b807c4abbab8/.travis.yml
  - export PATH=$HOME/.local/bin:$PATH
  - pip install requests-oauth  --user `whoami`
script:
  - npm test
after_success:
  - npm run coveralls
deploy:
  provider: npm
  email: ryan@ryanbreen.com
  on:
    tags: true
    all_branches: true
  api_key:
    secure: HhcCSWt/gIavho8apRa3+8UWgAesoJ1o2dvbhROviIZ+XNYBm5qCo1dfTH9d5hhaOVVVXe7rKLcqwru57fahXefU7gzPu78FuBQA5ipQnwQCZg8tLPVrq9FRGYUXOd/e/Al7NB9yVLaP6ji4KHC0lNUsEGMeo9mrH0hpKy9mc+k=
